/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.homeaway.streamplatform.hellostreams;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface OrderCommandEvents {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"OrderCommandEvents\",\"namespace\":\"com.homeaway.streamplatform.hellostreams\",\"types\":[{\"type\":\"record\",\"name\":\"OrderPlacedEvent\",\"doc\":\"Order Placed events\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"the unique id of this command event\"},{\"name\":\"orderId\",\"type\":\"string\",\"doc\":\"the unique orderId to be used for the order if it is created\"},{\"name\":\"customerId\",\"type\":\"string\",\"doc\":\"the id of the customer\"},{\"name\":\"item\",\"type\":\"string\",\"doc\":\"the item that is to be ordered\"},{\"name\":\"created\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"the timestamp that this order was placed\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends OrderCommandEvents {
    public static final org.apache.avro.Protocol PROTOCOL = com.homeaway.streamplatform.hellostreams.OrderCommandEvents.PROTOCOL;
  }
}